# Generated by Django 4.1.7 on 2023-07-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders_payment_done_amount_orders_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
